import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { AuthProvider } from "@/components/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
        <AuthProvider>
          <Navbar />
          <div className="container-fluid">
            <div className="row">
              <div className="col-md-3 col-lg-2 p-0">
                <Sidebar />
              </div>
              <main className="col-md-9 col-lg-10 px-4 py-4 min-vh-100 ">{children}</main>
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
